name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on perl ${{ matrix.perl_version }}
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        # buster, focal, bullseye/impish, 
        perl_version: [ 5.28.3, 5.30.3, 5.32.1, 5.34.0 ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup cache (perl)
      id: cache-perl
      uses: actions/cache@v2
      with:
        path: ~/perl5
        key: ${{ runner.os }}-perl-${{ matrix.perl_version }}

    - name: Install correct perl
      if: steps.cache-perl.outputs.cache-hit != 'true'
      run: |
          wget -qO - https://install.perlbrew.pl | bash
          ~/perl5/perlbrew/bin/perlbrew install --notest ${{ matrix.perl_version }}
          ~/perl5/perlbrew/bin/perlbrew clean

    - name: Add packages
      run: |
        ~/perl5/perlbrew/bin/perlbrew exec ./carton install
